const blogData = [
  {
    id:1,
    image: "https://images.unsplash.com/photo-1581090700227-1e8e5f1a04b3",
    date: "August 18, 2025",
    author: "Emily Carter",
    comments: "3 Comments",
    title: "Top 5 Tips for Painting Your Living Room",
    excerpt: "Transform your space with these easy and effective painting tips that even beginners can follow.",
    // link: "#",
  },
  {
    id:2,
    image: "https://images.unsplash.com/photo-1600573473235-7e05a1f99c8f",
    date: "July 10, 2025",
    author: "Liam Thompson",
    comments: "No Comments",
    title: "Why Primer is the Key to a Long-Lasting Paint Job",
    excerpt: "Before you dip your brush in paint, make sure you’re starting with the right foundation—primer!",
    // link: "#",
  },
  {
    id:3,
    image: "https://images.unsplash.com/photo-1578898887921-7c9e8e2a6f37",
    date: "June 22, 2025",
    author: "Sarah Lee",
    comments: "8 Comments",
    title: "The Psychology of Color: Choosing the Right Hue",
    excerpt: "Colors can affect your mood and productivity. Learn how to choose the right one for each room.",
    // link: "#",
  },
  {
    id:4,
    image: "https://images.unsplash.com/photo-1601987077766-cf74dc19d9cd",
    date: "May 14, 2025",
    author: "David Kim",
    comments: "2 Comments",
    title: "How to Use Painter's Tape Like a Pro",
    excerpt: "Avoid messy lines and bleeding edges with these essential tips for using painter’s tape.",
    // link: "#",
  },
  {
    id:5,
    image: "https://images.unsplash.com/photo-1626117561504-7b7b91bdfeb0",
    date: "April 2, 2025",
    author: "Anna Bell",
    comments: "6 Comments",
    title: "Paint Finishes Explained: Matte, Satin, and Gloss",
    excerpt: "Not sure which finish to choose? We break down the pros and cons of each type of paint finish.",
    // link: "#",
  },
  {
    id:6,
    image: "https://images.unsplash.com/photo-1615874959474-7c18024f26b4",
    date: "March 19, 2025",
    author: "Chris Walker",
    comments: "5 Comments",
    title: "10 Tools Every DIY Painter Should Own",
    excerpt: "From rollers to drop cloths, make sure you’re stocked with the tools that make painting a breeze.",
    // link: "#",
  },
  {
    id:7,
    image: "https://images.unsplash.com/photo-1628446088881-75800df3f9ef",
    date: "February 8, 2025",
    author: "Olivia Green",
    comments: "7 Comments",
    title: "How to Prep Your Walls Before Painting",
    excerpt: "Good prep leads to great results. Here’s how to get your walls ready for a flawless finish.",
    // link: "#",
  },
  {
    id:8,
    image: "https://images.unsplash.com/photo-1581287053829-8b7d93cb7655",
    date: "January 12, 2025",
    author: "Mark Johnson",
    comments: "1 Comment",
    title: "Eco-Friendly Paints: What You Need to Know",
    excerpt: "Protect your home and the planet by switching to sustainable, low-VOC paint options.",
    // link: "#",
  },
  {
    id:9,
    image: "https://images.unsplash.com/photo-1594322436404-81c6ad521b2d",
    date: "December 21, 2024",
    author: "Sophia Rivera",
    comments: "No Comments",
    title: "Feature Wall Ideas That Instantly Upgrade Any Room",
    excerpt: "Turn a boring wall into a bold statement with these creative and trendy ideas.",
    // link: "#",
  },
  {
    id:10,
    image: "https://images.unsplash.com/photo-1607083206173-9c1e4df7cf58",
    date: "November 30, 2024",
    author: "James Robinson",
    comments: "4 Comments",
    title: "Interior vs. Exterior Paint: What’s the Difference?",
    excerpt: "Don’t get them mixed up—understanding the difference can save you time and money.",
    // link: "#",
  },
];

export default blogData;
